# Generated by Django 5.2.5 on 2025-11-22 07:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_bankaccount_user_alter_budget_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'category_name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='budget_type',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number_masked',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account'), ('credit', 'Credit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('-10000.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_transactions', to='finance.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('-999999.99')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'category_name', 'category_type')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='transaction_user_id_6c2f76_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_9e98ba_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bank_account', 'transaction_date'], name='transaction_bank_ac_311bf8_idx'),
        ),
    ]
